logo: # add logo name
title: Discovery - A Responsive Minimal Blog Template
description: > # Discovery - A Responsive Minimal Blog Template

permalink: ':title/'
baseurl: "/discovery-jeyll" # the subpath of your site, e.g. /blog
url: "http://shagor.info" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
#author-pic: face.jpg # your photo
author-name: # FlexDThemes
about-author: # FlexDThemes
email: helpshagor@gmail.com # your email
phone: +8801783024879 # your pnone number
website: http://shagor.info # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

collections:
  portfolio:
